from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from ..models import BreakpointSpec, LaunchConfig, RegisterSnapshot


class EmulatorAdapter(Protocol):
    def launch(self, config: LaunchConfig) -> object: ...
    def connect(self) -> None: ...
    def load_state(self, state: Path) -> None: ...
    def run_vblanks(self, count: int) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def read_memory(self, address: int, size: int) -> bytes: ...
    def write_memory(self, address: int, data: bytes) -> None: ...
    def set_breakpoint(self, spec: BreakpointSpec) -> str: ...
    def clear_breakpoint(self, breakpoint_id: str) -> None: ...
    def get_registers(self) -> RegisterSnapshot: ...
    def set_pad_buttons(self, buttons: list[str]) -> list[str]: ...
    def clear_pad_buttons(self) -> int: ...
    def capture_screenshot(self, path: Path) -> None: ...
    def capture_vram(self, path: Path) -> None: ...
    def export_gpu_log(self, path: Path) -> None: ...
    def drain_events(self) -> list[dict[str, Any]]: ...
    def shutdown(self) -> None: ...
