local Json = Support.extra.dofile("json.lua")
local Base64 = Support.extra.dofile("base64.lua")
local Host = Support.extra.dofile("pcsx_redux_host.lua")
local Protocol = Support.extra.dofile("protocol.lua")
local Runner = Support.extra.dofile("experiment_runner.lua")
local Telemetry = Support.extra.dofile("telemetry.lua")
local host = Host.new(Json, Base64)
R4_AUTOLAB_HOST = host
local protocol = Protocol.new(host:writer(), host:json_codec())
local runner = Runner.new(host, protocol, Telemetry)

host:set_event_sender(function(message) protocol:send(message) end)
host:install_quitting_listener()
host:on_vblank(function() runner:on_vblank() end)
host:request_loop(function(request) runner:dispatch(request) end)
